#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
#Activate VirtualEnv in order to use the correct libraries
cartridge_type="python-2.6"
cd $OPENSHIFT_HOMEDIR/$cartridge_type/virtenv/bin 
source ./activate
python "$OPENSHIFT_REPO_DIR"wsgi/myblog/manage.py syncdb --noinput

  